### ISSUE TITLE
search-using-keywords: searching using keywords crashes the app

### ISSUE THREAD

**Issue by muljo** [sthoray/AllRight#123]
### Describe the bug
Related to #61 
On [search-using-keywords](https://github.com/sthoray/AllRight/tree/search-using-keywords) branch
The app returns you to the Main Activity when you search for an item (using keywords) in the Search Activity.
If you search for an item (using keywords again) in the SearchActivity; the app will crash.

### To Reproduce

Steps to reproduce the behaviour:

1. Search for an item in SearchActivity
2. App will return you to main menu
3. Search for an item in SearchActivity again.
3. App crashes.

### Expected behaviour

I expect that the app will make an API call to AllGoods, receive a successful response, update the SearchViewModel searchResponse to hold the response from AllGoods, and update the UI to show the items that have been searched for (and only those items).

### Device (please complete the following information)

- Device: Pixel 2
- OS: API 29
- App Version: [HEAD of search-using-keywords](https://github.com/sthoray/AllRight/tree/search-using-keywords)

### Additional context

The behaviour for the first 5 of 6 ticked boxes in #61 seems to be working fine.

Removing the 
```kotlin
        searchListingsResponse = null
```

**Comment by scsole** [comment]
<details>
  <summary>Crash exception</summary>

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sthoray.allright, PID: 5111
    kotlin.KotlinNullPointerException
        at com.sthoray.allright.ui.search.view.ResultsFragment$scrollListener$1.onScrolled(ResultsFragment.kt:121)
        at androidx.recyclerview.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:5173)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4231)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3862)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1695)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1695)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3470)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2938)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
</details>

The crash is due to the not null assertion operator (`!!`) in the `scrollListener`. The listener may be called when the keyboard disappears after searching, at which stage `searchListingsResponse` is already set to `null`.

A solution would be to only perform the `onScrolled` function when `searchListingsResponse` is not null. Possibly creating a new local variable `resultsPerPage` inside `ResultsFragment` would work better. In which case `resultsPerPage` could be set when a successful resource is observed and remove pagings dependancy from a resource which would stop paging from working if only one request failed: e.g. user lost mobile connectivity.

Aside: the keywords branch looks to be significantly behind master with lots of potential conflicts. I would consider merging the changes into your branch or intergrate your changes onto a new branch from the latest master.
